explorer: explorer.c
	gcc -o explorer explorer.c -I

generation: generation.c
	gcc -o generation generation.c -I

profilic: profilic.c
	gcc -o profilic profilic.c -I

slug: slug.c
	gcc -o slug slug.c -I

slugrace: slugrace.c
	gcc -o slugrace slugrace.c -I